server:
  port: 8502

spring:
  application:
    name: ticket-service

  datasource:
    url: jdbc:mysql://localhost:3306/microservice
    username: root
    password: root
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create

eurka:
  client:
    instance:
      hostname: localhost
    service-url:
      default-zone: http://localhost:8761/eureka/