server:
  port: 8501

spring:
  application:
    name: account-service
#  data:
#    cassandra:
#      keyspace:
#        name: keyspace
#        port: 9042
#        contact-points: 127.0.0.1

#  cloud:
#    config:
#      profile: native
#      uri: http://localhost:8888

eureka:
  client:
    instance:
      hostname: localhost
    serviceUrl:
      defaultZone: http://localhost:8500/eureka/

spcloud:
  cassandra:
    contact:
      point: 127.0.0.1
    port: 9042
    keyspace:
      name: springcloud

    username: cassandra
    password: cassandra