spring:
  cassandra:
    schema-action: CREATE_IF_NOT_EXISTS
    request:
      timeout: 10s
    connection:
      connect-timeout: 10s
        init-query-timeout: 10s
  application:
    name: account-service

  cloud:
    config:
      profile: native
      uri: http://localhost:8888
