server:
  port: 8500

spring:
  application:
    name: eureka-server
#  cloud:
#    config:
#      profile: native
#      uri: http://localhost:8888

eureka:
  server:
    eviction-interval-timer-in-ms: 1000
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8500/eureka/